project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    default: development
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: auto
        max_fee: null
        priority_fee: "10 gwei"
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings: null
    live:
        gas_limit: auto
        gas_buffer: 1.1
        gas_price: auto
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: false

dependencies:
    - smartcontractkit/chainlink-brownie-contracts@0.2.2
    - OpenZeppelin/openzeppelin-contracts@4.3.3

compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        remappings: 
            - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2'
            - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.3'
            - '@pooltogether_uniform_random=pooltogether/uniform-random-number@1.0.0'
            - '@pooltogether_sortition_sum_tree=pooltogether/sortition-sum-tree-factory@0.1.0'
    vyper:
        version: null

console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true
    editing_mode: emacs

reports:
    exclude_paths: null
    exclude_contracts: null
    only_include_project: true

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10
    phases:
        explicit: true
        reuse: true
        generate: true
        target: true
        shrink: true

autofetch_sources: false
dev_deployment_artifacts: false
dotenv: .env